### ISSUE TITLE
Deprecated use of UIApplication status bar setter in extension

### ISSUE THREAD

**Issue by Sndrsn** [huri000/SwiftEntryKit#128]
Disclaimer: This is my first issue or bug report, so I'll do my best to follow the template, but sorry ahead of time if I make a stupid mistake.

**Describe the bug**
Xcode generates a warning for the use of:

        UIApplication.shared.isStatusBarHidden = !appearance.visible
        UIApplication.shared.statusBarStyle = appearance.style

in the file UIApplication+EKAppearance.swift as:

Setter for 'isStatusBarHidden' was deprecated in iOS 9.0: Use -[UIViewController prefersStatusBarHidden]

because the status bar appearance is handled by the view controller directly now, as far as I understand it.

**To Reproduce**
1. Install SwiftEntryKit via cocoapods
2. Build

**Expected behavior**
No warning

**Screenshots**
N/A

**iPhone (please complete the following information):**
 - Device: iPhoneXR
 - iOS Version: iOS12
 - Xcode Version: 10.0
 - Dependency Manager Version: CocoaPods 1.5.3
 - SwiftEntryKit Release #: 0.8.2

**Additional context**

**Screenshots / Video Links**

**Comment by huri000** [comment]
Hi @Sndrsn! 
Yes, you are right about the deprecation, and it is indeed the best practice is to use the view-controller's computed variables (`prefersStatusBarStyle`/`Hidden`) to control the status bar appearance. 
Yet, lots of iOS applications still use `UIApplication` instance to change the appearance of the status bar. Therefore, I think it is up to the developer to decide and both ways are supported by `SwiftEntryKit`. You can read that [relevant section](https://github.com/huri000/SwiftEntryKit#status-bar) in the README.
Changing from one to the other must be supported in the project level, therfore, if you use `view controller baed statrus bar appearance`, you won't be able to use the other, and vice-versa.

To conclude, I prefer supporting both options and suffer deprecation warning, so that developers who still use the manual option would be able to do so. :-)

All in all, I think it's a good point, and every app I develop uses view controller based status bar appearance, but in a case of a library used by many, all options must be supported.

Thanks in any case.

**Comment by Sndrsn** [comment]
Oh, ok, that makes sense. I think I can just comment out those two lines if I want to remove the warnings, then.

**Comment by huri000** [comment]
I guess. But then you need to fork SwiftEntryKit and change these 2 lines yourself. 
You can silence pod warnings without the trouble as far as I remember, by adding designated command in your Podfile. Search it out. :-)
