### ISSUE TITLE
Using it on AppDelegate.swift

### ISSUE THREAD

**Issue by UtkuDalmaz** [huri000/SwiftEntryKit#129]
How can I use it in AppDelegate.swift

I want to show float notification when remote notification is received. 

So How to use it on AppDelegate?

**Comment by huri000** [comment]
Hi! You basically need to:
1. Implement push notification registration mechanism for your app - all the relevant methods in your application delegate.
2. Decide what content you want to display to the user.
3. Setup the pod-notification payload according to the content.
4. Upon push-notification arrival, extract the data from the payload (inside userInfo somewhere).
5. Follow the float example from the SwiftEntryKit sample project - setting the title, image, subtitle in the notification message.

Here is a [tutorial](https://www.raywenderlich.com/584-push-notifications-tutorial-getting-started) from Ray's website.

I hope that helps!

I'm closing the issue since it's neither a feature request nor a bug report.
