### ISSUE TITLE
use in extension !!

### ISSUE THREAD

**Issue by dverdugo85** [huri000/SwiftEntryKit#146]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by huri000** [comment]
Hi @dverdugo85! 
Could you please elaborate a bit more? 
What do you want to achieve? What are you trying to do? 
What component needs to be extended and to what end?

**Comment by dverdugo85** [comment]
@huri000 Hello!! I try to implement this inside a share extension! when display 

     let simpleMessage = EKSimpleMessage(image: image, title: title, description: description)
        let notificationMessage = EKNotificationMessage(simpleMessage: simpleMessage)
        
        let contentView = EKNotificationMessageView(with: notificationMessage)
        SwiftEntryKit.display(entry: contentView, using: attributes)
        


not working!! for float pop-ups!!!

Regards!!!

**Comment by dverdugo85** [comment]
@huri000I try to use  this code

        let coveringWindow = UIWindow(frame: (self.view.frame))
        SwiftEntryKit.display(entry: contentView, using: attribute, presentInsideKeyWindow: false, rollbackWindow: .custom(window: coveringWindow))


but the problem is the  value of windows in the extension!! In extension I not have access a this key!!

Regards!!!

**Comment by huri000** [comment]
I see. Share extension is a bit tricky. You don't have access to the key window because the layout structure is much different. 
Also, UIApplication's shared instance is unavailable (if you try to access it, I'll receive the following error:  <img width="540" alt="screen shot 2019-01-05 at 12 41 49 pm" src="https://user-images.githubusercontent.com/5504255/50723499-502b1000-10e7-11e9-88b3-dc887801e981.png">
So, it's impossible in the current `SwiftEntryKit` architecture to do what you wish to do. 
I doubt it's possible at all given the fact that one cannot even access the window of the view. Sorry!

**Comment by huri000** [comment]
I'm closing this issue but I'll love to know your thoughts on this anyway. Especially if you have found a workaround for this.
