### ISSUE TITLE
How to get text content from forms.

### ISSUE THREAD

**Issue by tosbaha** [huri000/SwiftEntryKit#15]
I am checking the example but I don't understand how we can get the text from the form. I tried to print out content of `textFields` from following code but it didn't print out the text that I entered.

```swift
    private func showSigninForm(attributes: EKAttributes, style: FormStyle) {
        let title = EKProperty.LabelContent(text: "Sign in to your account", style: style.title)
        let textFields = FormFieldPresetFactory.fields(by: [.email, .password], style: style)
        let button = EKProperty.ButtonContent(label: .init(text: "Continue", style: style.buttonTitle), backgroundColor: style.buttonBackground, highlightedBackgroundColor: style.buttonBackground.withAlphaComponent(0.8)) {
            print(textFields)

            SwiftEntryKit.dismiss()
        }
        let contentView = EKFormMessageView(with: title, textFieldsContent: textFields, buttonContent: button)
        SwiftEntryKit.display(entry: contentView, using: attributes)
    }
```

PS: If I want to lets say show a country picker for any textfield, where can I add the code? I couldn't find any action for textFields.

**Comment by huri000** [comment]
Hi @tosbaha,
1. You are right - I'll add in the callback content parameters (get the text out of the form).
2. Do you want to replace the input view for a text field with a picker - Is that what you intend to do?

**Comment by tosbaha** [comment]
I am trying to achieve the following. Having a two TextFields that I can get their content from and one extra disabled TextField. Upon clicking this disabled TextField I want to present a tableview to select the option. Something similar to https://github.com/dillidon/alerts-and-pickers Country picker. In its current state, I can't get text, disable TextField or have an action upon clicking.

**Comment by huri000** [comment]
I see. Now you are able to get the text out of the `EKProperty.TextFieldContent`, using version 0.2.1.

About other customizations to the text-fields - although they may be considered in future versions, SwiftEntryKit is currently not going to support a full customization of text-field presets because, in my opinion, those are out of the project's scope. You see, it's just there are too many ways to customize a text-field behavior (regex, delegation and callbacks, input views, etc...) and the presets are only meant to give developers a sense of "how to use".

However, In order to achieve that you can extract the internal form code into your project and modify it, or simply write your own entry.

Cheers!

**Comment by Burakpusat** [comment]
Hi there, I couldn't figure out how to get the data out of textfield. How do you do it in the example code snippet above?

**Comment by pauloec** [comment]
I'm having the same problem, did you find the answer @Burakpusat ?

**Comment by Burakpusat** [comment]
@pauloec Not really. I have decided to go with a different solution using a different alert view because of time limitations.
