### ISSUE TITLE
Dragging view doesn't work when using .positionConstraints.keyboardRelation with screen edge resistance

### ISSUE THREAD

**Issue by reececomo** [huri000/SwiftEntryKit#156]
**Describe the bug**
Hey there. Love the repo! When I set keyboard relation to offset with screen edge resistance - the view is no longer draggable (i.e. to dismiss the popup).
`attr.positionConstraints.keyboardRelation = .bind(offset: .init(bottom: 0, screenEdgeResistance: 20))`

It still works when I use:
`attr.positionConstraints.keyboardRelation = .bind(offset: .none)`

leading me to suspect this is an unintended side-effect. I would like to be able to dismiss the view without having to dismiss the keyboard first. I'd be happy to tackle the PR myself if this isn't intended behaviour.

**To Reproduce**
1. Set `EKAttributes().positionConstraints.keyboardRelation = .bind(offset: .none)`
2. Build and run, drag should work
3. Set `positionConstraints.keyboardRelation = .bind(offset: .init(bottom: 0, screenEdgeResistance: 20))`
4. Build and run, drag won't work

**Expected behavior**
Dragging to dismiss should still work when using screen edge resistance to vertically limit the keyboard offset position constraint in an SEK view.

**iPhone (please complete the following information):**
 - Device: All
 - iOS Version: 12.1
 - Xcode Version: 10
 - Dependency Manager Version: CocoaPods 1.5.3
 - SwiftEntryKit Release # 0.8.8

**Comment by huri000** [comment]
Hi @reececomo. What you describe is basically a consequence of trying to keep the entry within the screen bounds while the iPhone changes its orientation from portrait to landscape when the keyboard is in an open state. 

That led to preserving constraints like `resistanceConstraint`, that maintain the position of the entry in relation to the screen. You can call it intentional as fixing it might cause other various issues considering `SwiftEntryKit`'s current architecture.

Right now, I rather keep it that way than modify the current layout logic when handling keyboard.
Apologies for the delayed response.

**Comment by reececomo** [comment]
No worries @huri000, thanks for following up.
