### ISSUE TITLE
App Crashes when calling alert.show() with or without any arguments

### ISSUE THREAD

**Issue by 117MasterChief96** [huri000/SwiftEntryKit#194]
I added this to my project but cannot get it to work.  Everything I try calling any of the alert types I get `Warning: Attempt to present <UIAlertController: 0x7fb50503ee00> on <UINavigationController: 0x7fb504017600> whose view is not in the window hierarchy!`.  I got the example project working but it does not work in my project.  What am I doing wrong?

UPDATE: I have narrowed it down to `alert.show()` whenever it is called with or without args it causes this crash and error.

**Comment by huri000** [comment]
Could you send me an example project with a reproducible error?

**Comment by 117MasterChief96** [comment]
I tried creating a simple example project with the same error doing it exactly how I did in my actual project but cannot seem to get it to reproduce the error.  I did get it to work in my project by replacing the `alert.show()` with `self.present(alert, animated: true, completion: nil)` but cannot reproduce the error.  What would you like me to do since I could not seem to make a reproduction of the error?

**Comment by huri000** [comment]
Well, without a reproducible example I won't be able to look into it. In any case, you may want to look into which view controller presents the alert. In case `SwiftEntryKit`'s entry is being displayed, just make sure the sender is a view controller embedded in the entry so that the alert will be displayed in the proper window.
I'm closing this for now, but if you manage to reproduce the problem, just sample it and send it over.
Cheers.
