### ISSUE TITLE
Nothing being displayed

### ISSUE THREAD

**Issue by KyleGoslan** [huri000/SwiftEntryKit#280]
Nothing is displayed, am I missing something?

```
    var attributes = EKAttributes.default
    attributes.displayDuration = EKAttributes.DisplayDuration.infinity
    let vc = LoginViewController()
    vc.view.backgroundColor = .white
    SwiftEntryKit.display(entry: vc, using: attributes)
```

There isn't even an indiction that anything has been added to the view hierarchy in the debugger.

**Comment by huri000** [comment]
Have you taken a look at the example project. Are the samples there working for you? 
There can be multiple causes (constraints / wrong attributes), but it’s hard to know from this snippet.

**Comment by KyleGoslan** [comment]
Should this project compile without any further steps?
git clone --recurse-submodules https://github.com/huri000/SwiftEntryKit.git

I'm getting No such module 'QuickLayout'

**Comment by zjohnzheng** [comment]
Is your view controller made in the storyboard?
If so, you might need to set a storyboard identifier and do this:
```
let vc = storyboard.instantiateViewController(withIdentifier: "LoginViewControllerIdentifier") as! LoginViewController
```
Also, you could also try
`attributes.positionConstraints.size.height = .constant(value: UIScreen.main.bounds.size.height - CGFloat(100))` or something like that to make sure the constraints are right as @huri000 said.

**Comment by akshitzaveri** [comment]
@KyleGoslan I was getting the same error but then I did `pod install`.

**Comment by huri000** [comment]
Please retry again w/ one of the samples provided in the example project. It most like has something to do with missing or undefined constraints.
If it is a custom view from Nib, take a look at `NibExampleView`, otherwise please see how other presets are built.

Also, in case you want to enforce constant sizing on `LoginViewController`, `EKAttributes` has a  `PositionConstraints` construct that should allow you to do that. 

At this point, I'm closing this issue, but please let me knew if the problem persists. I may be able to help if you send me a small project.
