### ISSUE TITLE
Exclude keyWindow occupancy

### ISSUE THREAD

**Issue by liuzhiyi1992** [huri000/SwiftEntryKit#56]
**Is your feature request related to a problem? Please describe.**
EKWindow occupy application keyWindow while enrty attaching.
its overset any case to fetch correct application keyWindow, about present in keyWindow, about traversal with keyWindow

**Describe the solution you'd like**
should we show EKWindow used windowLevel-control like UIAlertViewController?  That would not disturb the hierarchy of application windows

**Describe alternatives you've considered**

**Additional context**
i wish the better development with SwiftEntryKit

**Comment by liuzhiyi1992** [comment]
haha, my mistake

**Comment by huri000** [comment]
Thanks for updating the issue!

> EKWindow occupy application keyWindow while enrty attaching.
its overset any case to fetch correct application keyWindow, about present in keyWindow, about traversal with keyWindow

I understand that if you have another window as key-window, replacing it and going back to the app key window will disturb the window hierarchy. You are right.

> should we show EKWindow used windowLevel-control like UIAlertViewController? That would not disturb the hierarchy of application windows

Do you mean present as modal view controller? Alerts are eventually presented in their own window so that's pretty much the same as what SwiftEntryKit does.

Maybe the right solution would be receiving a *fallback* window object to go back to.
When SwiftEntryKit has done displaying, the given fallback window would be set as key window.

What's your opinion?

**Comment by huri000** [comment]
Manipulating the window-hierarchy is what SwiftEntryKit is all about. As a solution to a situation of a fallback window (In which a developer already has a key window he wants the app to go back to), I'm gonna add a fallback window as a parameter to `present` and assign the main app window as its default value.

**Comment by huri000** [comment]
Resolved in 0.5.0 using an alternative window for a rollback.

**Comment by liuzhiyi1992** [comment]
morning huri000, i think fallback only is not good idea, key window position still occupied throughout the entry display with the different of system alert window, the problems that you cant uses key window to present or find some content in it hierarchy, simultaneously, it will terminate first responder while entry display, this causes infection to the behavious of host app
