### ISSUE TITLE
Example Not Working Properly

### ISSUE THREAD

**Issue by ios3** [huri000/SwiftEntryKit#82]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iPhone (please complete the following information):**
 - iOS Version: [e.g. iOS9.3]
 - Xcode Version [e.g. 9.3]
 - Dependency Manager Version [e.g. CocoaPods 1.5.2, Carthage 0.29.0]
 - SwiftEntryKit Release # [e.g. 0.2.0]

**Additional context**

**Screenshots / Video Links**

**Comment by huri000** [comment]
Please edit and explain the problem.

**Comment by kentonraiford** [comment]
I'm having a similar issue. It's telling me that "there's no such module QuickLayout."

**Comment by huri000** [comment]
@ios3, I'm closing this issue due to the absence of proper description.
@kentonraiford, this issue has already been resolved. Just stick to the [installation guide](https://github.com/huri000/SwiftEntryKit#example-project-installation) for the example project in the README.md.
Also, please review issue [#31](https://github.com/huri000/SwiftEntryKit/issues/31)
