### ISSUE TITLE
Display Multiple Entries At The Same Time

### ISSUE THREAD

**Issue by Blackjacx** [huri000/SwiftEntryKit#88]
**Is your feature request related to a problem? Please describe.**
I would like to display multiple entries at the same time. Lets say a subtle message as statusbar overlay that says when you're offline plus an other one that displays custom notifications / infos as popups. 

What I want to avoid is that the notifications dismiss the you're offline message.

**Comment by huri000** [comment]
Hi @Blackjacx,
That is a good idea but a really big one in terms of architectural change.
It changes the current premise on which the project is built upon - that only a single entry can be displayed at the same time. I've actually already begun implementing parts of it a couple of weeks ago. 
I really hope to be able to complete that feature in the near future.

In the meantime, if you don't want one entry to dismiss the other, you can set the display priority priority. See [DisplayPriority](https://github.com/huri000/SwiftEntryKit#display-priority).

**Comment by Blackjacx** [comment]
Cool looking forward to this change :-) Yep I think in the mean time I'll prioritize the offline message and drop the other ones.

Nice work btw :-)

**Comment by ralfboesch** [comment]
Hi @huri000 ,

we would love to have that feature aswell! :-)
In our case, it would be nice if we could show several Float Views at the same time.

Amazing framework nonetheless! 🍻

**Comment by huri000** [comment]
** A small update - **
One of the features I've been working on lately is an entry queue. 
Instead of being totally ignored or dropped in case of a low-display priority, entries will just wait for their turn (Until the queue is empty).
You will be able to decide whether you want to drop/override (like you do today) entries or enqueue them. You will also be able to decide how to prioritize the order - using the display-priority or a simple FIFO heuristic (chronological order)
I think it is necessary and should add an additional possibility to handle multiple entries.

In the future, there will be even more approaches to dealing with multiple entries.

**Comment by Blackjacx** [comment]
Wow thats awesome

**Comment by huri000** [comment]
@Blackjacx, @ralfboesch - Please see the new feature that suggests an alternative of entry queue, as of version 0.7.0.

**Comment by huri000** [comment]
Closing. As of today, there are multiple alternative solutions (mentioned above). I'm not sure this feature is needed anymore.

**Comment by Blackjacx** [comment]
This is perfectly fine now, thank you :-)
