### ISSUE TITLE
Objective-C compatibility

### ISSUE THREAD

**Issue by josecostamartins** [huri000/SwiftEntryKit#91]
**Is your feature request related to a problem? Please describe.**
How is the compatibility with objective-c code?

**Describe the solution you'd like**
To see how to use the library with objective-c

**Describe alternatives you've considered**
none so far

**Additional context**
I have a mixed objc-swift project (that we are migrating slowly and painfully) and I would like to use this awesome library

**Comment by huri000** [comment]
Thanks, @josecostamartins for opening the issue. Honestly, I haven't yet tried integrating SwiftEntryKit intro an existing Objective C project, and I think that's a good requirement. 
I'll look into it in the upcoming week to see if I can find an out-of-the-box solution to this.

**Comment by huri000** [comment]
Hi @josecostamartins! 
Sorry it took some time, but I investigated it a bit and my conclusions are:
1. SwiftEntryKit doesn't and won't support Objective-C by design since most of the APIs provided by `SwiftEntryKit` use Swift exclusive types.
2. SwiftEntryKit can be integrated pretty easily into an ObjC.
3. I created [this example project](https://github.com/huri000/ObjcEntryKitExample) that demonstrates how to do it in a straightforward manner.

Please let me know your thoughts.

**Comment by huri000** [comment]
For anyone who stumbles upon this issue as well. Please reference [Swift and Objective-C Interoperability](https://github.com/huri000/SwiftEntryKit#swift-and-objective-c-interoperability).

**Comment by josecostamartins** [comment]
Thank you very much for your time and knowledge
